[build]
  base = "./"
  publish = "apps/frontend/dist"
  functions = "netlify/functions"
  command = "pnpm --filter frontend... build"

[functions]
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true